name: Automated Tests

on: pull_request

jobs:
  jest:
    name: Jest Ubuntu
    runs-on: ubuntu-latest
    env:
      NODE_ENV: test
      PORT: 3000
      AWS_REGION: us-east-1
      DYNAMODB_ENDPOINT: http://localhost:4566
      JWT_SECRET: test-secret-key
      SALT_ROUNDS: 12
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: "lts/hydrogen"

      - run: npm ci

      - run: npm test